---
- hosts: all

  vars:
    jdk_url: null
    download_dir: "~{{ console_user | default(ansible_user) }}"

  tasks:

    - name: Downloads the tar.gz
      get_url:
        url: "{{ jdk_url }}"
        dest: "{{ download_dir }}/"
      register: downloaded_file

    - name: Extract the tar.gz
      unarchive:
        src: "{{ downloaded_file.dest }}"
        dest: "{{ download_dir }}"
        remote_src: yes
        list_files: yes
      register: archive_contents

    - name: Delete tar.gz file
      file:
        state: absent
        path: "{{ downloaded_file.dest }}"

    - name: Add JAVA_HOME to PATH
      lineinfile:
        dest: "{{ download_dir }}/.bashrc"
        state: present
        line: "export PATH=$JAVA_HOME/bin:$PATH"
        insertbefore: BOF

    - name: Update JAVA_HOME
      lineinfile:
        dest: "{{ download_dir }}/.bashrc"
        state: present
        regexp: '^export JAVA_HOME'
        line: "export JAVA_HOME={{ download_dir }}/{{ archive_contents.files[0].split('/')[0] }}"
        insertbefore: BOF
